const ANIMALS = [
  { id:401, name:"Cheetah", cost:17, size:5, tags:["Predator"], continents:["Africa"], appeal:6, conservation:0 },
  { id:402, name:"Lion", cost:16, size:4, tags:["Predator"], continents:["Africa"], appeal:9, conservation:0 },
  { id:403, name:"Leopard", cost:20, size:3, tags:["Predator", "Rock"], continents:["Africa"], appeal:7, conservation:1 },
  { id:404, name:"Caracal", cost:9, size:2, tags:["Predator"], continents:["Africa"], appeal:4, conservation:0 },
  { id:405, name:"Fennec Fox", cost:8, size:1, tags:["Predator"], continents:["Africa"], appeal:3, conservation:0 },
  { id:406, name:"Siberian Tiger", cost:30, size:5, tags:["Predator"], continents:["Asia"], appeal:10, conservation:2 },
  { id:407, name:"Sumatran Tiger", cost:26, size:4, tags:["Predator", "Water"], continents:["Asia"], appeal:8, conservation:2 },
  { id:408, name:"Sloth Bear", cost:14, size:3, tags:["Predator", "Bear"], continents:["Asia"], appeal:6, conservation:0 },
  { id:409, name:"Sun Bear", cost:16, size:2, tags:["Predator", "Bear"], continents:["Asia"], appeal:5, conservation:0 },
  { id:410, name:"Yellow-Throated Marten", cost:7, size:1, tags:["Predator"], continents:["Asia"], appeal:3, conservation:0 },
  { id:411, name:"Grizzly Bear", cost:22, size:5, tags:["Predator"], continents:["America"], appeal:9, conservation:0 },
  { id:412, name:"Jaguar", cost:16, size:4, tags:["Predator"], continents:["America"], appeal:8, conservation:0 },
  { id:413, name:"Cougar", cost:10, size:3, tags:["Predator", "Rock"], continents:["America"], appeal:5, conservation:0 },
  { id:414, name:"South American Coati", cost:11, size:2, tags:["Predator", "Bear", "Rock"], continents:["America"], appeal:4, conservation:0 },
  { id:415, name:"Raccoon", cost:11, size:1, tags:["Predator", "Bear"], continents:["America"], appeal:4, conservation:0 },
  { id:416, name:"Eurasian Brown Bear", cost:20, size:5, tags:["Predator", "Bear", "Water"], continents:["Europe"], appeal:8, conservation:0 },
  { id:417, name:"Wolf", cost:12, size:4, tags:["Predator"], continents:["Europe"], appeal:4, conservation:0 },
  { id:418, name:"Eurasian Lynx", cost:11, size:3, tags:["Predator"], continents:["Europe"], appeal:2, conservation:0 },
  { id:419, name:"European Badger", cost:5, size:2, tags:["Predator"], continents:["Europe"], appeal:3, conservation:0 },
  { id:420, name:"Stoat", cost:4, size:1, tags:["Predator"], continents:["Europe"], appeal:3, conservation:0 },
  { id:421, name:"New Zealand Fur Seal", cost:17, size:5, tags:["Predator", "Rock", "Water"], continents:["Australia"], appeal:8, conservation:0 },
  { id:422, name:"Australian Sea Lion", cost:18, size:4, tags:["Predator", "Water"], continents:["Australia"], appeal:7, conservation:1 },
  { id:423, name:"New Zealand Sea Lion", cost:17, size:3, tags:["Predator", "Water"], continents:["Australia"], appeal:6, conservation:0 },
  { id:424, name:"Australian Dingo", cost:13, size:2, tags:["Predator"], continents:["Australia"], appeal:3, conservation:0 },
  { id:425, name:"Tasmanian Devil", cost:11, size:1, tags:["Predator"], continents:["Australia"], appeal:4, conservation:0 },
  { id:426, name:"African Bush Elephant", cost:36, size:5, tags:["Herbivore"], continents:["Africa"], appeal:10, conservation:0 },
  { id:427, name:"White Rhinoceros", cost:24, size:4, tags:["Herbivore", "Rock"], continents:["Africa"], appeal:9, conservation:0 },
  { id:428, name:"Giraffe", cost:16, size:3, tags:["Herbivore"], continents:["Africa"], appeal:7, conservation:0 },
  { id:429, name:"Grevy'S Zebra", cost:12, size:2, tags:["Herbivore"], continents:["Africa"], appeal:6, conservation:0 },
  { id:430, name:"Pygmy Hippopotamus", cost:15, size:2, tags:["Herbivore", "Water"], continents:["Africa"], appeal:6, conservation:0 },
  { id:431, name:"Asian Elephant", cost:33, size:5, tags:["Herbivore", "Water"], continents:["Asia"], appeal:8, conservation:1 },
  { id:432, name:"Indian Rhinoceros", cost:25, size:4, tags:["Herbivore"], continents:["Asia"], appeal:9, conservation:0 },
  { id:433, name:"Giant Panda", cost:27, size:3, tags:["Herbivore", "Bear"], continents:["Asia"], appeal:10, conservation:2 },
  { id:434, name:"Red Panda", cost:16, size:2, tags:["Herbivore", "Bear"], continents:["Asia"], appeal:6, conservation:0 },
  { id:435, name:"Malayan Tapir", cost:17, size:2, tags:["Herbivore"], continents:["Asia"], appeal:5, conservation:0 },
  { id:436, name:"American Bison", cost:18, size:5, tags:["Herbivore"], continents:["America"], appeal:4, conservation:0 },
  { id:437, name:"Muskox", cost:13, size:4, tags:["Herbivore"], continents:["America"], appeal:5, conservation:0 },
  { id:438, name:"Reindeer", cost:12, size:3, tags:["Herbivore"], continents:["America"], appeal:5, conservation:0 },
  { id:439, name:"Lama", cost:10, size:2, tags:["Herbivore"], continents:["America"], appeal:4, conservation:0 },
  { id:440, name:"Mountain Tapir", cost:15, size:2, tags:["Herbivore", "Rock"], continents:["America"], appeal:4, conservation:1 },
  { id:441, name:"European Bison", cost:19, size:5, tags:["Herbivore"], continents:["Europe"], appeal:6, conservation:0 },
  { id:442, name:"Moose", cost:19, size:4, tags:["Herbivore"], continents:["Europe"], appeal:7, conservation:0 },
  { id:443, name:"Red Deer", cost:12, size:3, tags:["Herbivore"], continents:["Europe"], appeal:5, conservation:0 },
  { id:444, name:"Alpine Ibex", cost:10, size:2, tags:["Herbivore", "Rock"], continents:["Europe"], appeal:5, conservation:0 },
  { id:445, name:"Crested Porcupine", cost:8, size:1, tags:["Herbivore"], continents:["Europe"], appeal:3, conservation:0 },
  { id:446, name:"Dugong", cost:25, size:5, tags:["Herbivore", "Water"], continents:["Australia"], appeal:9, conservation:1 },
  { id:447, name:"Red Kangaroo", cost:23, size:4, tags:["Herbivore"], continents:["Australia"], appeal:7, conservation:0 },
  { id:448, name:"Koala", cost:21, size:3, tags:["Herbivore", "Bear", "Rock"], continents:["Australia"], appeal:8, conservation:0 },
  { id:449, name:"Platypus", cost:10, size:2, tags:["Herbivore", "Water"], continents:["Australia"], appeal:4, conservation:0 },
  { id:450, name:"Common Wombat", cost:9, size:2, tags:["Herbivore"], continents:["Australia"], appeal:4, conservation:0 },
  { id:451, name:"Proboscis Monkey", cost:32, size:5, tags:["Primate", "Rock"], continents:["Asia"], appeal:10, conservation:2 },
  { id:452, name:"Senegal Bushbaby", cost:10, size:1, tags:["Primate"], continents:["Africa"], appeal:1, conservation:0 },
  { id:453, name:"Collared Mangabey", cost:20, size:4, tags:["Primate"], continents:["Africa"], appeal:8, conservation:0 },
  { id:454, name:"Ring-Tailed Lemur", cost:12, size:3, tags:["Primate", "Rock"], continents:["Africa"], appeal:6, conservation:0 },
  { id:455, name:"Mantled Guereza", cost:13, size:3, tags:["Primate"], continents:["Africa"], appeal:6, conservation:0 },
  { id:456, name:"Barbary Macaque", cost:13, size:2, tags:["Primate"], continents:["Africa"], appeal:6, conservation:0 },
  { id:457, name:"Mandrill", cost:28, size:5, tags:["Primate"], continents:["Africa"], appeal:9, conservation:2 },
  { id:458, name:"Japanese Macaque", cost:18, size:3, tags:["Primate", "Water"], continents:["Asia"], appeal:7, conservation:0 },
  { id:459, name:"Red-Shanked Douc", cost:17, size:4, tags:["Primate"], continents:["Asia"], appeal:7, conservation:0 },
  { id:460, name:"Dusky-Leaf Monkey", cost:12, size:2, tags:["Primate"], continents:["Asia"], appeal:5, conservation:0 },
  { id:461, name:"Horsfield'S Tarsier", cost:14, size:1, tags:["Primate"], continents:["Asia"], appeal:3, conservation:0 },
  { id:462, name:"Northern Plains Gray Langur", cost:13, size:3, tags:["Primate", "Rock"], continents:["Asia"], appeal:6, conservation:0 },
  { id:463, name:"Panamanian White-Faced Capuchin", cost:11, size:2, tags:["Primate"], continents:["America"], appeal:5, conservation:0 },
  { id:464, name:"Brown Spider Monkey", cost:17, size:4, tags:["Primate"], continents:["America"], appeal:6, conservation:1 },
  { id:465, name:"Golden Lion Tamarin", cost:10, size:1, tags:["Primate"], continents:["America"], appeal:4, conservation:0 },
  { id:466, name:"Bolivian Red Howler", cost:12, size:3, tags:["Primate"], continents:["America"], appeal:6, conservation:0 },
  { id:467, name:"Ecuadorian Squirell Monkey", cost:12, size:2, tags:["Primate"], continents:["America"], appeal:5, conservation:0 },
  { id:468, name:"Cotton-Top Tamarin", cost:15, size:1, tags:["Primate"], continents:["America"], appeal:4, conservation:1 },
  { id:469, name:"Nile Crocodile", cost:13, size:5, tags:["Reptile", "Rock", "Water"], continents:["Africa"], appeal:9, conservation:0 },
  { id:470, name:"Western Green Mamba", cost:13, size:2, tags:["Reptile", "Rock"], continents:["Africa"], appeal:6, conservation:0 },
  { id:471, name:"African Spurred Tortoise", cost:22, size:3, tags:["Reptile", "Rock"], continents:["Africa"], appeal:6, conservation:1 },
  { id:472, name:"Rock Monitor", cost:12, size:2, tags:["Reptile", "Rock"], continents:["Africa"], appeal:5, conservation:0 },
  { id:473, name:"Common Agama", cost:9, size:1, tags:["Reptile", "Rock"], continents:["Africa"], appeal:3, conservation:0 },
  { id:474, name:"Indian Rock Python", cost:14, size:2, tags:["Reptile", "Rock"], continents:["Asia"], appeal:7, conservation:0 },
  { id:475, name:"King Cobra", cost:13, size:2, tags:["Reptile", "Rock"], continents:["Asia"], appeal:6, conservation:0 },
  { id:476, name:"Komodo Dragon", cost:14, size:3, tags:["Reptile", "Rock"], continents:["Asia"], appeal:2, conservation:0 },
  { id:477, name:"Veiled Chameleon", cost:14, size:1, tags:["Reptile", "Rock"], continents:["Asia"], appeal:4, conservation:0 },
  { id:478, name:"Chinese Water Dragon", cost:8, size:1, tags:["Reptile", "Rock", "Water"], continents:["Asia"], appeal:3, conservation:0 },
  { id:479, name:"American Alligator", cost:18, size:4, tags:["Reptile", "Rock", "Water"], continents:["America"], appeal:7, conservation:0 },
  { id:480, name:"Broad-Snouted Caiman", cost:16, size:4, tags:["Reptile", "Rock", "Water"], continents:["America"], appeal:6, conservation:0 },
  { id:481, name:"Galapagos Giant Tortoise", cost:30, size:3, tags:["Reptile", "Rock"], continents:["America"], appeal:8, conservation:2 },
  { id:482, name:"Anaconda", cost:13, size:2, tags:["Reptile", "Rock", "Water"], continents:["America"], appeal:6, conservation:0 },
  { id:483, name:"Boa Constrictor", cost:16, size:2, tags:["Reptile", "Rock"], continents:["America"], appeal:7, conservation:0 },
  { id:484, name:"European Pond Turtle", cost:9, size:1, tags:["Reptile", "Rock", "Water"], continents:["Europe"], appeal:4, conservation:0 },
  { id:485, name:"Common European Adder", cost:10, size:1, tags:["Reptile", "Rock"], continents:["Europe"], appeal:2, conservation:0 },
  { id:486, name:"Common Wall Lizard", cost:4, size:1, tags:["Reptile", "Rock"], continents:["Europe"], appeal:2, conservation:0 },
  { id:487, name:"European Grass Snake", cost:8, size:1, tags:["Reptile", "Rock", "Water"], continents:["Europe"], appeal:3, conservation:0 },
  { id:488, name:"Slow Worm", cost:4, size:1, tags:["Reptile", "Rock", "Water"], continents:["Europe"], appeal:2, conservation:0 },
  { id:489, name:"Saltwater Crocodile", cost:23, size:5, tags:["Reptile", "Rock", "Water"], continents:["Australia"], appeal:9, conservation:0 },
  { id:490, name:"Gould'S Monitor", cost:15, size:3, tags:["Reptile", "Rock"], continents:["Australia"], appeal:6, conservation:0 },
  { id:491, name:"Frilled Lizard", cost:12, size:2, tags:["Reptile", "Rock"], continents:["Australia"], appeal:5, conservation:0 },
  { id:492, name:"Inland Taipan", cost:10, size:2, tags:["Reptile", "Rock"], continents:["Australia"], appeal:5, conservation:0 },
  { id:493, name:"Thorny Devil", cost:6, size:1, tags:["Reptile", "Rock"], continents:["Australia"], appeal:3, conservation:0 },
  { id:494, name:"African Ostrich", cost:20, size:5, tags:["Bird"], continents:["Africa"], appeal:8, conservation:0 },
  { id:495, name:"Secretary Bird", cost:14, size:4, tags:["Bird"], continents:["Africa"], appeal:4, conservation:1 },
  { id:496, name:"Marabou", cost:10, size:3, tags:["Bird"], continents:["Africa"], appeal:4, conservation:0 },
  { id:497, name:"Lesser Flamingo", cost:15, size:2, tags:["Bird", "Water"], continents:["Africa"], appeal:6, conservation:0 },
  { id:498, name:"Shoebill", cost:9, size:1, tags:["Bird"], continents:["Africa"], appeal:3, conservation:1 },
  { id:499, name:"Cinereous Vulture", cost:16, size:5, tags:["Bird"], continents:["Asia"], appeal:6, conservation:0 },
  { id:500, name:"Long-Billed Vulture", cost:20, size:4, tags:["Bird", "Rock"], continents:["Asia"], appeal:5, conservation:1 },
  { id:501, name:"Indian Peafowl", cost:18, size:3, tags:["Bird"], continents:["Asia"], appeal:7, conservation:0 },
  { id:502, name:"Great Hornbill", cost:13, size:2, tags:["Bird"], continents:["Asia"], appeal:6, conservation:0 },
  { id:503, name:"Snowy Owl", cost:11, size:1, tags:["Bird"], continents:["Asia"], appeal:4, conservation:0 },
  { id:504, name:"Andean Condor", cost:17, size:5, tags:["Bird", "Rock"], continents:["America"], appeal:7, conservation:0 },
  { id:505, name:"Bald Eagle", cost:23, size:4, tags:["Bird", "Water"], continents:["America"], appeal:8, conservation:0 },
  { id:506, name:"King Vulture", cost:12, size:3, tags:["Bird"], continents:["America"], appeal:9, conservation:0 },
  { id:507, name:"Greater Rhea", cost:12, size:2, tags:["Bird"], continents:["America"], appeal:5, conservation:0 },
  { id:508, name:"Scarlet Macaw", cost:16, size:1, tags:["Bird"], continents:["America"], appeal:4, conservation:0 },
  { id:509, name:"Golden Eagle", cost:20, size:5, tags:["Bird", "Rock"], continents:["Europe"], appeal:7, conservation:0 },
  { id:510, name:"White Stork", cost:9, size:4, tags:["Bird"], continents:["Europe"], appeal:4, conservation:0 },
  { id:511, name:"Greater Flamingo", cost:16, size:3, tags:["Bird", "Water"], continents:["Europe"], appeal:7, conservation:0 },
  { id:512, name:"Eurasian Eagle-Owl", cost:10, size:2, tags:["Bird"], continents:["Europe"], appeal:4, conservation:0 },
  { id:513, name:"Barn Owl", cost:12, size:1, tags:["Bird"], continents:["Europe"], appeal:3, conservation:0 },
  { id:514, name:"Emu", cost:22, size:5, tags:["Bird"], continents:["Australia"], appeal:7, conservation:0 },
  { id:515, name:"Australian Pelican", cost:13, size:4, tags:["Bird", "Water"], continents:["Australia"], appeal:5, conservation:0 },
  { id:516, name:"Norhtern Cassowary", cost:12, size:3, tags:["Bird"], continents:["Australia"], appeal:6, conservation:0 },
  { id:517, name:"Laughing Kookaburra", cost:9, size:2, tags:["Bird"], continents:["Australia"], appeal:0, conservation:0 },
  { id:518, name:"Lesser Bird-Of-Paradise", cost:15, size:1, tags:["Bird"], continents:["Australia"], appeal:5, conservation:0 },
  { id:519, name:"(Domestic) Goat", cost:7, size:1, tags:["Petting Zoo"], continents:[], appeal:0, conservation:0 },
  { id:520, name:"Sheep", cost:7, size:1, tags:["Petting Zoo"], continents:[], appeal:0, conservation:0 },
  { id:521, name:"Horse", cost:7, size:1, tags:["Petting Zoo"], continents:[], appeal:0, conservation:0 },
  { id:522, name:"Donkey", cost:7, size:1, tags:["Petting Zoo"], continents:[], appeal:0, conservation:0 },
  { id:523, name:"Domestic Rabbit", cost:7, size:1, tags:["Petting Zoo"], continents:[], appeal:0, conservation:0 },
  { id:524, name:"Mangalica", cost:7, size:1, tags:["Petting Zoo"], continents:[], appeal:0, conservation:0 },
  { id:525, name:"Guinea Pig", cost:7, size:1, tags:["Petting Zoo"], continents:[], appeal:0, conservation:0 },
  { id:526, name:"Alpaca", cost:7, size:1, tags:["Petting Zoo"], continents:[], appeal:0, conservation:0 },
  { id:527, name:"Coconut Lorikeet", cost:7, size:1, tags:["Petting Zoo"], continents:[], appeal:0, conservation:0 },
  { id:528, name:"Bennett'S Wallaby", cost:7, size:1, tags:["Petting Zoo"], continents:[], appeal:0, conservation:0 },
  { id:529, name:"Magnificent Sea Anemone", cost:6, size:1, tags:["Sea Animal"], continents:["Australia"], appeal:3, conservation:0 },
  { id:530, name:"Orange Clownfish", cost:10, size:1, tags:["Sea Animal"], continents:["Australia"], appeal:3, conservation:0 },
  { id:531, name:"Palette Surgeonfish", cost:9, size:1, tags:["Sea Animal"], continents:["Asia"], appeal:4, conservation:0 },
  { id:532, name:"Zooplankton", cost:4, size:1, tags:["Sea Animal"], continents:[], appeal:1, conservation:0 },
  { id:533, name:"Blackside Hawkfish", cost:11, size:2, tags:["Sea Animal"], continents:["Australia"], appeal:4, conservation:0 },
  { id:534, name:"Southern Blue-Ringed Octopus", cost:12, size:2, tags:["Sea Animal"], continents:["Australia"], appeal:4, conservation:0 },
  { id:535, name:"Sharknose Goby", cost:7, size:1, tags:["Sea Animal"], continents:["America"], appeal:2, conservation:0 },
  { id:536, name:"Lonhorn Cowfish", cost:9, size:2, tags:["Sea Animal"], continents:["Africa"], appeal:4, conservation:0 },
  { id:537, name:"Blackbar Triggerfish", cost:14, size:2, tags:["Sea Animal"], continents:["Africa"], appeal:5, conservation:0 },
  { id:538, name:"Devil Firefish", cost:16, size:2, tags:["Sea Animal"], continents:["Asia"], appeal:6, conservation:0 },
  { id:539, name:"American Whitespotted Filefish", cost:12, size:1, tags:["Sea Animal"], continents:["America"], appeal:5, conservation:0 },
  { id:540, name:"Guineafowl Puffer", cost:15, size:2, tags:["Sea Animal"], continents:["Asia"], appeal:5, conservation:0 },
  { id:541, name:"Bluespotted Ribbontail Ray", cost:16, size:2, tags:["Sea Animal"], continents:["Asia"], appeal:7, conservation:0 },
  { id:542, name:"Humphead Wrasse", cost:22, size:3, tags:["Sea Animal"], continents:["Africa"], appeal:6, conservation:1 },
  { id:543, name:"Coastal Manta Ray", cost:23, size:5, tags:["Sea Animal"], continents:["Asia"], appeal:8, conservation:0 },
  { id:544, name:"Caribbean Reef Shark", cost:20, size:4, tags:["Sea Animal", "Predator"], continents:["America"], appeal:5, conservation:0 },
  { id:545, name:"Longcomb Sawfish", cost:21, size:4, tags:["Sea Animal"], continents:["Africa"], appeal:9, conservation:1 },
  { id:546, name:"Sand Tiger Shark", cost:32, size:5, tags:["Sea Animal", "Predator", "Rock"], continents:["Australia"], appeal:8, conservation:1 },
  { id:547, name:"Mediterranean Rainbow Wrasse", cost:8, size:1, tags:["Sea Animal", "Rock"], continents:["Europe"], appeal:3, conservation:0 },
  { id:548, name:"Short-Snouted Seahorse", cost:7, size:1, tags:["Sea Animal", "Rock"], continents:["Europe"], appeal:2, conservation:0 },
  { id:549, name:"Common Octopus", cost:9, size:3, tags:["Sea Animal", "Rock"], continents:["Europe"], appeal:5, conservation:0 },
  { id:550, name:"Compass Jellyfish", cost:10, size:3, tags:["Sea Animal"], continents:["Europe"], appeal:6, conservation:0 },
  { id:551, name:"Loggerhead Sea Turtle", cost:23, size:4, tags:["Sea Animal", "Reptile", "Rock"], continents:["Europe"], appeal:8, conservation:0 },
  { id:552, name:"Green Sea Turtle", cost:17, size:3, tags:["Sea Animal", "Reptile", "Rock"], continents:["America"], appeal:6, conservation:0 },
  { id:553, name:"Tambaqui", cost:15, size:1, tags:["Sea Animal", "Herbivore"], continents:["America"], appeal:5, conservation:0 },
  { id:554, name:"African Penguin", cost:18, size:3, tags:["Sea Animal", "Bird", "Rock", "Water"], continents:["Africa"], appeal:6, conservation:0 },
  { id:555, name:"Golden Snub-Nosed Monkey", cost:18, size:3, tags:["Primate", "Rock"], continents:["Asia"], appeal:6, conservation:1 },
  { id:556, name:"Wolverine", cost:15, size:3, tags:["Predator", "Bear", "Rock"], continents:["Europe"], appeal:5, conservation:0 },
  { id:557, name:"Vietnamese Pot-Bellied Pig", cost:7, size:1, tags:["Petting Zoo"], continents:[], appeal:0, conservation:0 },
  { id:558, name:"Northern Muriqui", cost:16, size:4, tags:["Primate", "Rock"], continents:["America"], appeal:6, conservation:1 },
  { id:559, name:"Coquerel'S Sifaka", cost:17, size:3, tags:["Primate", "Rock"], continents:["Africa"], appeal:7, conservation:0 },
  { id:560, name:"Brahminy Kite", cost:12, size:3, tags:["Bird", "Rock", "Water"], continents:["Australia"], appeal:6, conservation:0 },
];